version: '3.2'

networks:
  wan:
    external: true
  internal:

services:
  server:
    image: ${DOMOTICZ_IMAGE}
    networks:
      - wan
      - internal
    ports:
      - "${DOMOTICZ_PORT}:8080"
    links:
      - miio-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/config:/config
      - ./data/scripts/lua:/domoticz/scripts/lua
      - ./data/scripts/actions:/domoticz/scripts/actions
      - ./data/zigate:/domoticz/plugins/Domoticz-Zigate/Data
    labels:
      - "traefik.enable=true"
      - "traefik.backend=domoticz"
      - "traefik.docker.network=wan"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:${HOSTNAME}"
      - "traefik.frontend.auth.basic=${AUTH}"
    privileged: true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  miio-server:
    image: ${MIIO_SERVER_IMAGE}
    networks:
      - internal
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
